baseURL = 'https://perplex0204.github.io/ttting999-blog/'
languageCode = 'zh-tw'
title = 'My Personal Blog'
theme = 'newsroom'

[params]
  author = "Your Name"
  description = "My personal blog"
  version = "1.0.0"

[caches]
  [caches.images]
    dir = ":cacheDir/images"
